spring.application.name=entregasGestor
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/deliverymanager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_SECRET:my-secret-key}
#springdoc.api-docs.enable=false
#springdoc.swagger-ui.enabled=false